apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-h2h
spec:
  podSelector:
    matchLabels:
      app: fifa-h2h
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-group
spec:
  podSelector:
    matchLabels:
      app: fifa-group
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-tournament
spec:
  podSelector:
    matchLabels:
      app: fifa-tournament
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress