
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifa-h2h
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fifa-h2h
  template:
    metadata:
      labels:
        app: fifa-h2h
    spec:
      containers:
      - name: fifa-h2h
        image: 276096488420.dkr.ecr.ap-south-1.amazonaws.com/fifa/h2h:3
        ports:
        - containerPort: 8501

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"