apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifa-main-page
  
  labels:
    app: fifa-main-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fifa-main-page
  template:
    metadata:
      labels:
        app: fifa-main-page
    spec:
      containers:
        - name: fifa-main-page
          image: 276096488420.dkr.ecr.ap-south-1.amazonaws.com/fifa/main-page:11
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi