apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fifa-tournament
  name: fifa-tournament
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fifa-tournament

  template:
    metadata:
      labels:
        app: fifa-tournament
    spec:
      containers:
      - image: 276096488420.dkr.ecr.ap-south-1.amazonaws.com/fifa/tournament:11
        name: fifa-tournament
        ports:
        - containerPort: 8501

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
       

